<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2019/2/19
 * Time: 21:11
 */

class ApiException extends \think\exception\Handle
{
    public function render(Exception $e)
    {


        return parent::render($e); // TODO: Change the autogenerated stub
    }
}